name: Flask Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

      # Step 5: Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # Step 6: Authenticate Heroku CLI
      - name: Authenticate Heroku CLI
        run: |
          echo -e "machine api.heroku.com\n  login heroku\n  password HRKU-85d198a3-2bf7-49eb-ac04-c4147027b11f\nmachine git.heroku.com\n  login heroku\n  password HRKU-85d198a3-2bf7-49eb-ac04-c4147027b11f" > ~/.netrc
          chmod 600 ~/.netrc

      # Step 7: Set Heroku Remote
      - name: Set Heroku Remote
        run: |
          git remote add heroku https://git.heroku.com/med-gen-ai-backend.git

      # Step 8: Deploy to Heroku
      - name: Deploy to Heroku
        run: |
          git push heroku main --force

      # Step 9: Scale web dyno
      - name: Scale web dyno
        run: |
          heroku ps:scale web=1 --app med-gen-ai-backend
